from .start_kb import start_kb
from .inline_menu_kb import menu_kb
from .categories_keyboard import category_kb
from .subcategories_kb import subcategories_kb
from .settings_kb import settings_kb
from .product_kb import product_kb
from .product_numbers_kb import numbers_kb
from .basket_kb import basket_kb
from .locations_kb import locations_kb
from .delivery_type_kb import delivery_type
from .time_kb import time_kb
from .payment_system_type_kb import system_type_kb
from .payment_type_kb import payment_type_kb
from .money_type_kb import money_kb
from .order_list_kb import order_list_kb